# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Install uv
    - pip install uv
    # Install the project with docs dependencies
    - uv pip install --system ".[docs]"
    # Build the docs
    - export COLUMNS=80 && export TQDM_NCOLS=80 && uv run sphinx-build docs $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
