"""Configuration module defining example events."""

from tests.functional.trackers.conftest import (
    start_experiment_event,
    stop_experiment_event,
    model_registration_event,
    actor_registration_event,
    save_model_event,
    load_model_event,
    start_training_event,
    start_epoch_event,
    end_epoch_event,
    iterate_batch_event,
    terminated_training_event,
    end_training_event,
    start_test_event,
    end_test_event,
    metrics_event,
    update_learning_rate_event,
    string_stream,
    event_workflow,
    allow_event_creation_outside_scope,
)

_fixtures = (
    start_experiment_event,
    stop_experiment_event,
    model_registration_event,
    actor_registration_event,
    save_model_event,
    load_model_event,
    start_training_event,
    start_epoch_event,
    end_epoch_event,
    iterate_batch_event,
    terminated_training_event,
    end_training_event,
    start_test_event,
    end_test_event,
    metrics_event,
    update_learning_rate_event,
    string_stream,
    event_workflow,
    allow_event_creation_outside_scope,
)
